(#160) Improve messages in Assertion and Mismatches
llorllale/cactoos-matchers pull request #231
Opened 2021-02-14 19:50 UTC by victornoel

This is for #160. I tried to cleanup a bit how Assertion and Mismatches behave and so that it's consistent with all the matchers.

2021-02-15 17:28 UTC, victornoel commented
@0crat status

2021-02-15 18:07 UTC, 0crat commented
> @0crat status ([here](https://github.com/llorllale/cactoos-matchers/issues/231#issuecomment-779362975))

@victornoel This is what I know about this job in C63314D6Z, as in [§32](http://www.zerocracy.com/policy.html#32):

  * The job [#231](https://github.com/llorllale/cactoos-matchers/issues/231) is [in scope](http://www.zerocracy.com/policy.html#14) for 22hr
  * The role is `REV`
  * The job is assigned to @baudoliver7[/z](https://www.0crat.com/u/baudoliver7) for [21hr](http://www.zerocracy.com/policy.html#8)
  * There is no monetary reward attached, it's a [free](http://www.zerocracy.com/policy.html#2) job
  * The job doesn't have any [impediments](http://www.zerocracy.com/policy.html#9)
  * The [budget](http://www.zerocracy.com/policy.html#4) is 15 minutes/points
  * These users are banned and won't be assigned:
    * @victornoel[/z](https://www.0crat.com/u/victornoel): This user reported the ticket
  * Job [footprint](https://www.0crat.com/footprint/C63314D6Z?q=%7Bjob%3A%27gh%3Allorllale%2Fcactoos-matchers%23231%27%2Ctype%3A%7B%24not%3A%2F%5ENotify%2F%7D%7D) (restricted area)

<!-- https://www.0crat.com/footprint/C63314D6Z/9777ef13-0cea-4e4d-8aed-0b82f16604de, version: 0.55, hash: ${buildNumber} -->

2021-02-15 23:15 UTC, baudoliver7 requested changes
@victornoel Please, see comments below.

2021-02-17 17:44 UTC, victornoel commented on src/test/java/org/llorllale/cactoos/matchers/MismatchesTest.java
> +            "Must mismatches",
@baudoliver7 arg, again :) thx!

2021-02-17 17:45 UTC, victornoel commented on src/main/java/org/llorllale/cactoos/matchers/HasValues.java
>                      .appendValue(new TextOf(expected)),
@baudoliver7 good find, and I looked around and didn't find any similar thing in the codebase too :)

2021-02-17 17:45 UTC, victornoel commented
@baudoliver7 it should be ok now

2021-02-17 17:56 UTC, baudoliver7 commented
@victornoel Thanks, it's ok for me :)

2021-02-17 18:42 UTC, victornoel commented
@rultor merge

2021-02-17 18:43 UTC, rultor commented
> @rultor merge

@victornoel OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/24143-780766668)

2021-02-17 18:50 UTC, merged

2021-02-17 18:51 UTC, rultor commented
> @rultor merge

@victornoel Done! FYI, the full log is [here](https://www.rultor.com/t/24143-780766668) (took me 8min)

2021-02-17 19:12 UTC, 0crat commented
@sereshqua[/z](https://www.0crat.com/u/sereshqua) please review this job completed by @baudoliver7[/z](https://www.0crat.com/u/baudoliver7), as in [§30](http://www.zerocracy.com/policy.html#30); the job will be fully closed and all payments will be made when the quality review is completed

<!-- https://www.0crat.com/footprint/C63314D6Z/d8d9fbbd-eece-42ce-a1c2-e93ab6297954, version: 0.55, hash: ${buildNumber} -->

2021-02-20 06:56 UTC, sereshqua commented
@0crat quality good